name: dmarc_parser
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  xml: ^6.5.0
  pdf: ^3.11.0
  printing: ^5.13.1
  file_picker: ^8.0.6

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.7

flutter:
  uses-material-design: true

msix_config:
  display_name: DMARC Parser
  publisher_display_name: IntelPeak Technologies
  identity_name: com.intelpeaktech.dmarch_parser
  msix_version: 1.0.0.0
  logo_path: C:\path\to\logo.png
  capabilities: internetClient, location, microphone, webcam, printing
